from typing import Dict, Set, List, Tuple, Optional
from .classes import CFG, BasicBlock, BlockType
import re


class DataFlowAnalyzer:
    """Performs data flow analysis on a CFG"""
    
    def __init__(self, cfg: CFG):
        self.cfg = cfg
        self.variables: Set[str] = set()
        self._extract_variables()
    
    def _extract_variables(self):
        """Extract all variable names from CFG"""
        for block in self.cfg.blocks.values():
            for stmt in block.statements:
                # Simple regex to find variable names
                vars_in_stmt = re.findall(r'\b([a-zA-Z_][a-zA-Z0-9_]*)\b', stmt.text)
                self.variables.update(vars_in_stmt)
        
        # Remove Python keywords
        keywords = {
            'if', 'else', 'elif', 'for', 'while', 'return', 'def', 'class',
            'import', 'from', 'try', 'except', 'finally', 'with', 'as',
            'pass', 'break', 'continue', 'and', 'or', 'not', 'in', 'is',
            'True', 'False', 'None', 'lambda', 'yield', 'assert', 'raise',
            'del', 'global', 'nonlocal', 'async', 'await', 'match', 'case'
        }
        self.variables -= keywords
    
    def reaching_definitions(self) -> Dict[int, Set[Tuple[int, str]]]:
        """
        Compute reaching definitions for each block.
        
        A definition reaches a point if there is a path from the definition
        to that point along which the variable is not redefined.
        
        Returns:
            Dict mapping block_id -> set of (defining_block_id, variable_name)
        """
        # Initialize GEN and KILL sets
        gen = {}   # Definitions generated by each block
        kill = {}  # Definitions killed by each block
        
        # For each block, compute GEN and KILL
        for block_id, block in self.cfg.blocks.items():
            gen[block_id] = set()
            kill[block_id] = set()
            
            for stmt in block.statements:
                # Find assignments (simple heuristic)
                if '=' in stmt.text and not any(op in stmt.text for op in ['==', '!=', '<=', '>=']):
                    # Extract variable being assigned to
                    parts = stmt.text.split('=')
                    if len(parts) >= 2:
                        lhs = parts[0].strip()
                        # Handle multiple assignments, tuples, etc.
                        var_match = re.match(r'^([a-zA-Z_][a-zA-Z0-9_]*)', lhs)
                        if var_match:
                            var = var_match.group(1)
                            if var in self.variables:
                                gen[block_id].add((block_id, var))
                                
                                # Kill all other definitions of this variable
                                for other_block in self.cfg.blocks:
                                    if other_block != block_id:
                                        kill[block_id].add((other_block, var))
        
        # Iterative data flow analysis
        reach_in = {bid: set() for bid in self.cfg.blocks}
        reach_out = {bid: set() for bid in self.cfg.blocks}
        
        changed = True
        iterations = 0
        max_iterations = 100
        
        while changed and iterations < max_iterations:
            changed = False
            iterations += 1
            
            for block_id, block in self.cfg.blocks.items():
                # IN[B] = Union of OUT[P] for all predecessors P
                new_in = set()
                for pred_id in block.predecessors:
                    new_in |= reach_out.get(pred_id, set())
                
                # OUT[B] = GEN[B] ∪ (IN[B] - KILL[B])
                new_out = gen[block_id] | (new_in - kill[block_id])
                
                if new_in != reach_in[block_id] or new_out != reach_out[block_id]:
                    reach_in[block_id] = new_in
                    reach_out[block_id] = new_out
                    changed = True
        
        return reach_in
    
    def live_variables(self) -> Dict[int, Set[str]]:
        """
        Compute live variables at the entry of each block.
        
        A variable is live at a point if it may be used along some path
        from that point before being redefined.
        
        Returns:
            Dict mapping block_id -> set of live variables
        """
        # Compute USE and DEF for each block
        use = {}  # Variables used before being defined
        define = {}  # Variables defined
        
        for block_id, block in self.cfg.blocks.items():
            use[block_id] = set()
            define[block_id] = set()
            defined_in_block = set()
            
            for stmt in block.statements:
                # Find all variables in statement
                vars_in_stmt = re.findall(r'\b([a-zA-Z_][a-zA-Z0-9_]*)\b', stmt.text)
                
                # Check if this is an assignment
                is_assignment = '=' in stmt.text and '==' not in stmt.text and '<=' not in stmt.text and '>=' not in stmt.text
                
                if is_assignment:
                    parts = stmt.text.split('=', 1)
                    if len(parts) == 2:
                        lhs = parts[0].strip()
                        rhs = parts[1].strip()
                        
                        # Variables on RHS are used
                        rhs_vars = re.findall(r'\b([a-zA-Z_][a-zA-Z0-9_]*)\b', rhs)
                        for v in rhs_vars:
                            if v in self.variables and v not in defined_in_block:
                                use[block_id].add(v)
                        
                        # Variable on LHS is defined
                        lhs_match = re.match(r'^([a-zA-Z_][a-zA-Z0-9_]*)', lhs)
                        if lhs_match:
                            lhs_var = lhs_match.group(1)
                            if lhs_var in self.variables:
                                define[block_id].add(lhs_var)
                                defined_in_block.add(lhs_var)
                else:
                    # All variables are uses
                    for v in vars_in_stmt:
                        if v in self.variables and v not in defined_in_block:
                            use[block_id].add(v)
        
        # Backward data flow analysis
        live_in = {bid: set() for bid in self.cfg.blocks}
        live_out = {bid: set() for bid in self.cfg.blocks}
        
        changed = True
        iterations = 0
        
        while changed and iterations < 100:
            changed = False
            iterations += 1
            
            # Process in reverse (backward analysis)
            for block_id, block in self.cfg.blocks.items():
                # OUT[B] = Union of IN[S] for all successors S
                new_out = set()
                for succ_id, _ in block.successors:
                    new_out |= live_in.get(succ_id, set())
                
                # IN[B] = USE[B] ∪ (OUT[B] - DEF[B])
                new_in = use[block_id] | (new_out - define[block_id])
                
                if new_in != live_in[block_id] or new_out != live_out[block_id]:
                    live_in[block_id] = new_in
                    live_out[block_id] = new_out
                    changed = True
        
        return live_in
    
    def def_use_chains(self) -> Dict[Tuple[int, str], Set[Tuple[int, int]]]:
        """
        Compute def-use chains.
        
        For each definition, find all uses that it may reach.
        
        Returns:
            Dict mapping (defining_block, variable) -> set of (using_block, statement_index)
        """
        reaching = self.reaching_definitions()
        chains = {}
        
        for block_id, block in self.cfg.blocks.items():
            # Find uses in this block
            for stmt_idx, stmt in enumerate(block.statements):
                vars_used = re.findall(r'\b([a-zA-Z_][a-zA-Z0-9_]*)\b', stmt.text)
                
                for var in vars_used:
                    if var in self.variables:
                        # Find all reaching definitions of this variable
                        for def_block, def_var in reaching[block_id]:
                            if def_var == var:
                                key = (def_block, var)
                                if key not in chains:
                                    chains[key] = set()
                                chains[key].add((block_id, stmt_idx))
        
        return chains
    
    def find_unused_variables(self) -> List[Tuple[int, str]]:
        """
        Find variables that are defined but never used.
        
        Returns:
            List of (block_id, variable_name) tuples
        """
        chains = self.def_use_chains()
        unused = []
        
        # Find all definitions
        all_defs = set()
        for block_id, block in self.cfg.blocks.items():
            for stmt in block.statements:
                if '=' in stmt.text and '==' not in stmt.text:
                    parts = stmt.text.split('=')
                    if len(parts) >= 2:
                        lhs = parts[0].strip()
                        var_match = re.match(r'^([a-zA-Z_][a-zA-Z0-9_]*)', lhs)
                        if var_match:
                            var = var_match.group(1)
                            if var in self.variables:
                                all_defs.add((block_id, var))
        
        # Check which definitions have no uses
        for def_block, var in all_defs:
            if (def_block, var) not in chains or len(chains[(def_block, var)]) == 0:
                unused.append((def_block, var))
        
        return unused


class CodeSmellDetector:
    """Detects code smells using rule-based analysis"""
    
    def __init__(self, cfg: CFG, source_code: str):
        self.cfg = cfg
        self.source_code = source_code
        self.lines = source_code.split('\n')
    
    def detect_all(self) -> List[Dict]:
        """Run all smell detection rules"""
        smells = []
        
        smells.extend(self.detect_long_function())
        smells.extend(self.detect_high_complexity())
        smells.extend(self.detect_deep_nesting())
        smells.extend(self.detect_too_many_parameters())
        smells.extend(self.detect_magic_numbers())
        smells.extend(self.detect_duplicate_code())
        smells.extend(self.detect_god_function())
        smells.extend(self.detect_empty_except())
        smells.extend(self.detect_boolean_trap())
        
        # Add unused variables from data flow analysis
        analyzer = DataFlowAnalyzer(self.cfg)
        unused = analyzer.find_unused_variables()
        for block_id, var in unused:
            smells.append({
                "type": "unused_variable",
                "severity": "low",
                "message": f"Variable '{var}' is defined but never used",
                "block_id": block_id,
                "location": f"block {block_id}"
            })
        
        return smells
    
    def detect_long_function(self, threshold: int = 50) -> List[Dict]:
        """Detect functions that are too long"""
        smells = []
        line_count = len([line for line in self.lines if line.strip()])
        
        if line_count > threshold:
            smells.append({
                "type": "long_function",
                "severity": "medium",
                "message": f"Function has {line_count} lines (threshold: {threshold})",
                "line_count": line_count,
                "threshold": threshold
            })
        
        return smells
    
    def detect_high_complexity(self, threshold: int = 10) -> List[Dict]:
        """Detect high cyclomatic complexity"""
        smells = []
        cc = self.cfg.calculate_cyclomatic_complexity()
        
        if cc > threshold:
            severity = "critical" if cc > 20 else "high" if cc > 15 else "medium"
            smells.append({
                "type": "high_complexity",
                "severity": severity,
                "message": f"Cyclomatic complexity is {cc} (threshold: {threshold})",
                "complexity": cc,
                "threshold": threshold
            })
        
        return smells
    
    def detect_deep_nesting(self, threshold: int = 4) -> List[Dict]:
        """Detect deeply nested code"""
        smells = []
        max_depth = self.cfg.calculate_nesting_depth()
        
        if max_depth > threshold:
            severity = "high" if max_depth > 6 else "medium"
            smells.append({
                "type": "deep_nesting",
                "severity": severity,
                "message": f"Maximum nesting depth is {max_depth} (threshold: {threshold})",
                "nesting_depth": max_depth,
                "threshold": threshold
            })
        
        return smells
    
    def detect_too_many_parameters(self, threshold: int = 5) -> List[Dict]:
        """Detect functions with too many parameters"""
        smells = []
        
        # Count parameters from first line
        first_line = self.lines[0] if self.lines else ""
        if 'def ' in first_line:
            # Extract parameters
            match = re.search(r'def\s+\w+\s*\((.*?)\)', first_line)
            if match:
                params = match.group(1)
                param_list = [p.strip() for p in params.split(',') if p.strip() and p.strip() != 'self']
                param_count = len(param_list)
                
                if param_count > threshold:
                    smells.append({
                        "type": "too_many_parameters",
                        "severity": "medium",
                        "message": f"Function has {param_count} parameters (threshold: {threshold})",
                        "parameter_count": param_count,
                        "threshold": threshold
                    })
        
        return smells
    
    def detect_magic_numbers(self) -> List[Dict]:
        """Detect magic numbers (hardcoded numbers)"""
        smells = []
        magic_numbers = []
        
        for line_no, line in enumerate(self.lines, 1):
            # Find numbers that aren't 0, 1, or -1
            numbers = re.findall(r'\b(\d+)\b', line)
            for num in numbers:
                if num not in ['0', '1'] and len(num) > 1:
                    magic_numbers.append({
                        "number": num,
                        "line": line_no,
                        "code": line.strip()
                    })
        
        if magic_numbers:
            smells.append({
                "type": "magic_numbers",
                "severity": "low",
                "message": f"Found {len(magic_numbers)} magic numbers",
                "occurrences": magic_numbers[:5]  # Show first 5
            })
        
        return smells
    
    def detect_duplicate_code(self, min_lines: int = 3) -> List[Dict]:
        """Detect duplicate code blocks"""
        smells = []
        
        # Simple duplicate detection: look for repeated sequences of lines
        line_sequences = {}
        for i in range(len(self.lines) - min_lines + 1):
            sequence = tuple(self.lines[i:i+min_lines])
            sequence_str = '\n'.join(sequence).strip()
            
            if sequence_str:  # Ignore empty sequences
                if sequence_str in line_sequences:
                    line_sequences[sequence_str].append(i)
                else:
                    line_sequences[sequence_str] = [i]
        
        duplicates = {seq: lines for seq, lines in line_sequences.items() if len(lines) > 1}
        
        if duplicates:
            smells.append({
                "type": "duplicate_code",
                "severity": "medium",
                "message": f"Found {len(duplicates)} duplicate code blocks",
                "duplicate_count": len(duplicates)
            })
        
        return smells
    
    def detect_god_function(self, threshold: int = 100) -> List[Dict]:
        """Detect 'God Functions' - functions that do too much"""
        smells = []
        
        # Count responsibilities (simplified heuristic)
        line_count = len([line for line in self.lines if line.strip()])
        statement_count = sum(len(block.statements) for block in self.cfg.blocks.values())
        decision_count = self.cfg.count_decision_points()
        
        # God function indicators
        is_god_function = (
            line_count > 50 and
            decision_count > 10 and
            statement_count > 80
        )
        
        if is_god_function:
            smells.append({
                "type": "god_function",
                "severity": "critical",
                "message": f"Function is doing too much ({line_count} lines, {decision_count} decisions)",
                "metrics": {
                    "lines": line_count,
                    "statements": statement_count,
                    "decisions": decision_count
                },
                "recommendation": "Split into multiple focused functions based on responsibility"
            })
        
        return smells

    def detect_empty_except(self) -> List[Dict]:
        """Detect empty except blocks (code smell)"""
        smells = []
        
        for line_no, line in enumerate(self.lines, 1):
            if 'except' in line:
                # Check if next line is pass or empty
                if line_no < len(self.lines):
                    next_line = self.lines[line_no].strip() if line_no < len(self.lines) else ""
                    if next_line == "pass" or not next_line:
                        smells.append({
                            "type": "empty_except",
                            "severity": "high",
                            "message": f"Empty except block at line {line_no}",
                            "line": line_no,
                            "recommendation": "Always handle exceptions or at least log them"
                        })
        
        return smells

    def detect_boolean_trap(self) -> List[Dict]:
        """Detect boolean parameters (boolean trap anti-pattern)"""
        smells = []
        
        # Check first line for boolean parameters
        first_line = self.lines[0] if self.lines else ""
        if 'def ' in first_line:
            match = re.search(r'def\s+\w+\s*\((.*?)\)', first_line)
            if match:
                params = match.group(1)
                # Look for True/False in parameter defaults
                if 'True' in params or 'False' in params:
                    smells.append({
                        "type": "boolean_trap",
                        "severity": "low",
                        "message": "Boolean parameters can make code unclear",
                        "recommendation": "Use enums or separate methods instead of boolean flags"
                    })
        
        return smells


class ComplexityHotspotDetector:
    """Detects complexity hotspots in the CFG"""
    
    def __init__(self, cfg: CFG):
        self.cfg = cfg
    
    def detect_hotspots(self) -> List[Dict]:
        """Detect all types of complexity hotspots"""
        hotspots = []
        
        hotspots.extend(self._detect_high_complexity())
        hotspots.extend(self._detect_high_branching())
        hotspots.extend(self._detect_loop_complexity())
        hotspots.extend(self._detect_deep_nesting())
        
        return hotspots
    
    def _detect_high_complexity(self) -> List[Dict]:
        """Detect overall high complexity"""
        hotspots = []
        cc = self.cfg.calculate_cyclomatic_complexity()
        
        if cc > 10:
            severity = "critical" if cc > 20 else "high"
            hotspots.append({
                "type": "high_overall_complexity",
                "severity": severity,
                "message": f"Function has cyclomatic complexity of {cc}",
                "complexity": cc,
                "recommendation": "Consider breaking this function into smaller functions"
            })
        
        return hotspots
    
    def _detect_high_branching(self) -> List[Dict]:
        """Detect blocks with many outgoing branches"""
        hotspots = []
        
        for block_id, block in self.cfg.blocks.items():
            branch_count = len(block.successors)
            
            if branch_count > 3:
                hotspots.append({
                    "type": "high_branching",
                    "severity": "medium",
                    "message": f"Block {block_id} has {branch_count} outgoing branches",
                    "block_id": block_id,
                    "branch_count": branch_count,
                    "recommendation": "Consider using polymorphism or strategy pattern"
                })
        
        return hotspots
    
    def _detect_loop_complexity(self) -> List[Dict]:
        """Detect complex loops"""
        hotspots = []
        loop_count = self.cfg.count_loops()
        
        if loop_count > 2:
            hotspots.append({
                "type": "many_loops",
                "severity": "medium",
                "message": f"Function contains {loop_count} loops",
                "loop_count": loop_count,
                "recommendation": "Consider extracting loop bodies into separate functions"
            })
        
        # Check for nested loops (back edges within back edges)
        back_edges = self.cfg._find_back_edges()
        nested_loops = 0
        
        for src, dst in back_edges:
            # Check if there are other back edges in the path from dst to src
            if self._has_nested_loop(dst, src, back_edges):
                nested_loops += 1
        
        if nested_loops > 0:
            hotspots.append({
                "type": "nested_loops",
                "severity": "high",
                "message": f"Detected {nested_loops} nested loops",
                "nested_count": nested_loops,
                "recommendation": "Nested loops can be hard to understand and optimize"
            })
        
        return hotspots
    
    def _has_nested_loop(self, start: int, end: int, back_edges: List[Tuple[int, int]]) -> bool:
        """Check if there's a nested loop in the path"""
        for src, dst in back_edges:
            if src != start and dst != end:
                # Simple heuristic: check if this back edge is between start and end
                if start <= src <= end and start <= dst <= end:
                    return True
        return False
    
    def _detect_deep_nesting(self) -> List[Dict]:
        """Detect deep nesting"""
        hotspots = []
        max_depth = self.cfg.calculate_nesting_depth()
        
        if max_depth > 4:
            severity = "high" if max_depth > 6 else "medium"
            hotspots.append({
                "type": "deep_nesting",
                "severity": severity,
                "message": f"Maximum nesting depth is {max_depth}",
                "nesting_depth": max_depth,
                "recommendation": "Use guard clauses or extract nested logic into functions"
            })
        
        return hotspots
    

class HalsteadMetrics:
    """
    Calculate Halstead Complexity Metrics
    
    Measures:
    - Program vocabulary
    - Program length
    - Calculated program length
    - Volume
    - Difficulty
    - Effort
    """
    
    def __init__(self, source_code: str):
        self.source = source_code
        self.operators = set()
        self.operands = set()
        self.operator_count = 0
        self.operand_count = 0
        self._analyze()
    
    def _analyze(self):
        """Analyze code for operators and operands"""
        # Python operators
        op_patterns = [
            r'\+', r'-', r'\*', r'/', r'%', r'\*\*',
            r'==', r'!=', r'<', r'>', r'<=', r'>=',
            r'and', r'or', r'not', r'in', r'is',
            r'=', r'\+=', r'-=', r'\*=', r'/=',
            r'if', r'else', r'elif', r'for', r'while',
            r'def', r'return', r'class', r'import'
        ]
        
        for line in self.source.split('\n'):
            line = line.strip()
            if not line or line.startswith('#'):
                continue
            
            # Count operators
            for op in op_patterns:
                matches = re.findall(r'\b' + op + r'\b', line)
                if matches:
                    self.operators.add(op)
                    self.operator_count += len(matches)
            
            # Count operands (variables, literals)
            words = re.findall(r'\b[a-zA-Z_][a-zA-Z0-9_]*\b', line)
            for word in words:
                if word not in ['if', 'else', 'elif', 'for', 'while', 'def', 'return', 'class']:
                    self.operands.add(word)
                    self.operand_count += 1
    
    def calculate(self) -> Dict:
        """Calculate all Halstead metrics"""
        n1 = len(self.operators)  # Unique operators
        n2 = len(self.operands)   # Unique operands
        N1 = self.operator_count  # Total operators
        N2 = self.operand_count   # Total operands
        
        if n1 == 0 or n2 == 0:
            return {
                "vocabulary": 0,
                "length": 0,
                "volume": 0,
                "difficulty": 0,
                "effort": 0
            }
        
        import math
        
        vocabulary = n1 + n2
        length = N1 + N2
        volume = length * math.log2(vocabulary) if vocabulary > 0 else 0
        difficulty = (n1 / 2) * (N2 / n2) if n2 > 0 else 0
        effort = difficulty * volume
        
        return {
            "vocabulary": vocabulary,
            "length": length,
            "calculated_length": n1 * math.log2(n1) + n2 * math.log2(n2) if n1 > 0 and n2 > 0 else 0,
            "volume": round(volume, 2),
            "difficulty": round(difficulty, 2),
            "effort": round(effort, 2),
            "time_to_program": round(effort / 18, 2),  # seconds (Halstead's formula)
            "bugs_delivered": round(volume / 3000, 3)  # Expected bugs
        }


def generate_refactoring_suggestions(cfg: CFG, smells: List[Dict], hotspots: List[Dict]) -> List[Dict]:
    """
    Generate refactoring suggestions based on detected smells and hotspots.
    
    Returns prioritized list of refactoring suggestions.
    """
    suggestions = []
    
    # High complexity
    cc = cfg.calculate_cyclomatic_complexity()
    if cc > 15:
        suggestions.append({
            "priority": "critical",
            "refactoring": "Extract Method",
            "reason": f"Cyclomatic complexity is {cc}",
            "benefit": "Improves readability and testability",
            "steps": [
                "Identify logical sections of the function",
                "Extract each section into a separate method",
                "Ensure each extracted method has CC < 10"
            ]
        })
    
    # Deep nesting
    if cfg.calculate_nesting_depth() > 4:
        suggestions.append({
            "priority": "high",
            "refactoring": "Replace Nested Conditional with Guard Clauses",
            "reason": "Deep nesting detected",
            "benefit": "Flattens control flow and improves readability",
            "steps": [
                "Identify nested if statements",
                "Convert to guard clauses with early returns",
                "Invert conditions where appropriate"
            ]
        })
    
    # Many loops
    if cfg.count_loops() > 2:
        suggestions.append({
            "priority": "medium",
            "refactoring": "Extract Loop Bodies",
            "reason": "Multiple loops detected",
            "benefit": "Improves code organization and reusability",
            "steps": [
                "Extract loop body into a separate function",
                "Use list comprehensions where applicable",
                "Consider using functional programming patterns (map, filter)"
            ]
        })
    
    # Unused variables (from smells)
    unused_vars = [s for s in smells if s['type'] == 'unused_variable']
    if unused_vars:
        suggestions.append({
            "priority": "low",
            "refactoring": "Remove Dead Code",
            "reason": f"Found {len(unused_vars)} unused variables",
            "benefit": "Reduces confusion and improves maintainability",
            "steps": [
                "Remove unused variable definitions",
                "Check if removal affects any side effects"
            ]
        })
    
    # Magic numbers
    magic_numbers = [s for s in smells if s['type'] == 'magic_numbers']
    if magic_numbers:
        suggestions.append({
            "priority": "low",
            "refactoring": "Replace Magic Numbers with Named Constants",
            "reason": "Magic numbers detected",
            "benefit": "Improves code self-documentation",
            "steps": [
                "Define constants at the top of the file",
                "Use descriptive names",
                "Replace hardcoded values with constants"
            ]
        })
    
    return suggestions


def run_complete_static_analysis(cfg: CFG, source_code: str) -> Dict:
    """
    Run complete static analysis and return structured results.
    
    This is the main function to call for getting all static analysis data.
    
    Returns:
        Complete analysis including data flow, smells, hotspots, and suggestions
    """
    # Data flow analysis
    analyzer = DataFlowAnalyzer(cfg)
    
    try:
        reaching = analyzer.reaching_definitions()
        live_vars = analyzer.live_variables()
        def_use = analyzer.def_use_chains()
        unused = analyzer.find_unused_variables()
    except Exception as e:
        print(f"Data flow analysis error: {e}")
        reaching = {}
        live_vars = {}
        def_use = {}
        unused = []
    
    # Code smell detection
    smell_detector = CodeSmellDetector(cfg, source_code)
    smells = smell_detector.detect_all()
    
    # Hotspot detection
    hotspot_detector = ComplexityHotspotDetector(cfg)
    hotspots = hotspot_detector.detect_hotspots()
    
    # Refactoring suggestions
    suggestions = generate_refactoring_suggestions(cfg, smells, hotspots)
    
    # Metrics
    metrics = cfg.get_comprehensive_metrics()

    # Halstead metrics
    try:
        halstead = HalsteadMetrics(source_code)
        halstead_metrics = halstead.calculate()
    except Exception as e:
        print(f"Halstead metrics error: {e}")
        halstead_metrics = {}
    
    # Format output
    result = {
        "metrics": metrics,
        "halstead":halstead_metrics,
        "data_flow": {
            "reaching_definitions_count": len(reaching),
            "live_variables_count": sum(len(vars) for vars in live_vars.values()),
            "def_use_chains_count": len(def_use),
            "unused_variables": [{"block": block_id, "variable": var} for block_id, var in unused]
        },
        "code_smells": smells,
        "hotspots": hotspots,
        "refactoring_suggestions": suggestions,
        "summary": {
            "total_smells": len(smells),
            "total_hotspots": len(hotspots),
            "critical_issues": len([s for s in smells if s.get('severity') == 'critical']) + 
                              len([h for h in hotspots if h.get('severity') == 'critical']),
            "high_priority_suggestions": len([s for s in suggestions if s.get('priority') == 'critical'])
        }
    }
    
    return result